apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector: #Linking the ClusterIp to a sets of Pods with a same label below
    app: myapp
    type: backend



# CusterIP Commands
# kubectl create -f service-defination.yaml
# kubectl get services
