apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 300008
  selector: ## This is labels used in the pods we want to connect the service  to
    app: myapp
    type: frontend


## Commands in Service
# kubectl create -f service-definition.yaml : To create a Service
# kubectl get services: To see the list of all the services

# Using MINIKUBE for NODE
# minikube service my-service-name --url : to get the IP address of the NODE and the PORT the service we just created is listening to
