# How to create a deploymnet

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: frontend
spec: ##Pod
  selector:
    matchLabels:
      app: myapp
      type: frontend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec: ## Container
      containers:
        - name: nginx-contrainer
          image: nginx
  replicas: 3



