# Docker Compose

# Docker Compose is a better way of setting up a complex application running mutilple services. 

# How to link a container depending on another container together
# - docker run -d --name=vogueapi -p 3100:3100 --link redis:redis vote-app
# docker run -d --name=clickcounter --link redis:redis -p 8085:5000 kodekloud/click-counter
# run -v /opt/data:/var/lib/mysql -d --name mysql-db -e MYSQL_ROOT_PASSWORD=db_pass123 mys
version: 2
services:
  redis:
    image: redis

  db:
    image: postgre:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  vote:
    image: voting-app
    build: ./vote #For Build option if the image is not on DOCKER HUB
    ports:
      - 5000:80
    links:
      - redis
    depends_on: #This is use show which service to start before one , if they depend on one another
      - db

  result:
    image: result-app
    ports:
      - 5001:80
    links:
      - db

  worker:
    image: result-app
    ports:
      - 5001:80
    links:
      - redis
      - db


# NOTE: For Version:3 we dont need to use Link because we deploy the application with a docker-compose file, 
# it will automatically create a network for these containers, and connect all containers to that network. 
# All container within that network will be able to talk to each other without using (links)


version: 3
services:
  redis:
    image: redis:alpine
  clickcounter:
    image: kodekloud/click-counter
    ports:
     - 8085:5000

## VOTING APP PROJECT
## https://github.com/dockersamples/example-voting-app
